### ISSUE TITLE
[enhancement] Improvements in code

### ISSUE THREAD

**Issue by xMinota** [xMinota/wushi#1]
### Overall improvements which can be made
- [x] Use classes instead of `module.exports` for commands.
- [x] Initialize the bot using a Class extending to `discord.Client()`
- [ ] Use MongoDB instead of QuickDB for better efficiency. (`mongoose`) (will do after release)
- [x] Create a JSON for items/collectables/foodstuffs so it can be easily accessed for better usage. 
- [ ] ~~Possibly transfer to `TypeScript`?~~

**Comment by relative** [comment]
No

**Comment by relative** [comment]
Yes

**Comment by relative** [comment]
c

**Comment by xMinota** [comment]
MongoDB databasing for a proper stable release.

**Comment by relative** [comment]
cool

**Comment by xMinota** [comment]
answer dm retartard

**Comment by xMinota** [comment]
I ended up doing like all of this.
